import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './style.css';

const API = import.meta.env.VITE_API_URL || 'http://localhost:8787';
const TAGS = { RPG: ['final fantasy','dragon quest','persona','tales of','ys','trails'], Action: ['assassin','dark souls','monster hunter','resident evil'], Indie: ['hollow knight','celeste','stardew','hades'], Strategy: ['civilization','xcom','total war'] };
function authHeaders(token){ return { 'Content-Type':'application/json', Authorization:`Bearer ${token}` }; }
function imgUrl(appid){ return `https://cdn.cloudflare.steamstatic.com/steam/apps/${appid}/capsule_616x353.jpg`; }
function gameImage(game){ return game.wide_capsule_url || game.header_url || game.capsule_url || imgUrl(game.appid || game.app_id); }
function hydrateGame(g){ const name=(g.name||'').toLowerCase(); return { ...g, tags:Object.entries(TAGS).filter(([,terms])=>terms.some(t=>name.includes(t))).map(([tag])=>tag), achievements:g.achievements||{total:g.achievement_total??0,unlocked:g.achievement_unlocked??0,percent:g.achievement_percent??null} }; }
async function api(token,path,options={}){ const r=await fetch(`${API}${path}`,{...options,headers:{...authHeaders(token),...(options.headers||{})}}); const data=await r.json().catch(()=>({})); if(!r.ok) throw new Error(data.error||'Request failed'); return data; }

function App(){
  const [token,setToken]=useState(localStorage.getItem('steamToken'));
  const [user,setUser]=useState(null); const [settings,setSettings]=useState({featured_game_ids:[],featured_collection_ids:[],layout_style:'hero',achievement_display_mode:'byGame',card_density:'comfortable',accent_color:'#3b82f6'});
  const [games,setGames]=useState([]); const [page,setPage]=useState('library'); const [query,setQuery]=useState(''); const [tag,setTag]=useState('all'); const [sort,setSort]=useState('alpha');
  const [status,setStatus]=useState(''); const [syncing,setSyncing]=useState(false); const [collections,setCollections]=useState({mine:[],saved:[]}); const [achievementGame,setAchievementGame]=useState(null);

  useEffect(()=>{ const u=new URL(location.href); const t=u.searchParams.get('token'); if(t){localStorage.setItem('steamToken',t); setToken(t); history.replaceState({},'',location.pathname);} },[]);
  useEffect(()=>{ if(token) loadAll(); },[token]);
  useEffect(()=>{ document.documentElement.style.setProperty('--accent', settings.accent_color || '#3b82f6'); },[settings.accent_color]);

  async function loadAll(){ try{ const me=await api(token,'/api/me'); setUser(me.user); const s=normalizeSettings(me.settings||{}); setSettings(s); const lib=await api(token,'/api/library'); setGames((lib.games||[]).map(hydrateGame)); await loadCollections(); }catch(e){ setStatus(e.message); } }
  async function loadCollections(){ const data=await api(token,'/api/collections'); setCollections(data); }
  function normalizeSettings(s){ return {accent_color:'#3b82f6',...s, featured_game_ids:parseList(s.featured_game_ids), featured_collection_ids:parseList(s.featured_collection_ids)}; }
  function parseList(v){ if(Array.isArray(v)) return v; try{return JSON.parse(v||'[]')}catch{return []} }
  async function initialImport(){ setStatus('Importing library once...'); const d=await api(token,'/api/library/import',{method:'POST'}); setStatus(`Imported ${d.imported} games. Achievements are not fetched until you sync batches.`); await loadAll(); }
  async function refreshLibrary(){ setStatus('Checking Steam library for missing games...'); const d=await api(token,'/api/library/refresh',{method:'POST'}); setStatus(`Checked ${d.checked} games and added ${d.added} missing games.`); await loadAll(); }
  async function syncAchievements(force=false){ setSyncing(true); setStatus(force?'Force syncing next achievement batch...':'Syncing next due achievement batch...'); try{ const d=await api(token,'/api/achievements/sync',{method:'POST',body:JSON.stringify({limit:8,force})}); setStatus(`Processed ${d.processed}; synced ${d.synced}; skipped ${d.skipped}; errors ${d.errors}; ${d.remainingReadyToSync} still due.`); await loadAll(); }finally{ setSyncing(false); } }
  async function saveProfile(next){ setSettings(next); const me=await api(token,'/api/settings',{method:'PUT',body:JSON.stringify(next)}); setSettings(normalizeSettings(me.settings)); }

  const stats=useMemo(()=>{ const ach=games.filter(g=>g.achievements.percent!==null); const total=ach.reduce((s,g)=>s+g.achievements.total,0); const unlocked=ach.reduce((s,g)=>s+g.achievements.unlocked,0); return {totalGames:games.length,achievementGames:ach.length,totalAchievements:total,unlockedAchievements:unlocked,perfectGames:ach.filter(g=>g.achievements.percent===100).length,overallPercent:total?Math.round(unlocked/total*100):0}; },[games]);
  const visibleGames=useMemo(()=>{ let list=games.filter(g=>g.name?.toLowerCase().includes(query.toLowerCase())); if(tag!=='all') list=list.filter(g=>g.tags.includes(tag)); if(sort==='alpha') list.sort((a,b)=>a.name.localeCompare(b.name)); if(sort==='percent') list.sort((a,b)=>(b.achievements.percent??-1)-(a.achievements.percent??-1)); if(sort==='playtime') list.sort((a,b)=>(b.playtime_forever||0)-(a.playtime_forever||0)); return list; },[games,query,tag,sort]);
  const featuredGames=useMemo(()=>{ const ids=settings.featured_game_ids.map(String); const picked=games.filter(g=>ids.includes(String(g.appid))); return picked.length?picked:[...games].sort((a,b)=>(b.achievements.percent??-1)-(a.achievements.percent??-1)).slice(0,6); },[games,settings.featured_game_ids]);
  function toggleFeatured(appid){ const id=String(appid); const ids=settings.featured_game_ids.map(String); saveProfile({...settings,featured_game_ids:ids.includes(id)?ids.filter(x=>x!==id):[...ids,id].slice(-12)}); }

  if(!token) return <main className="hero"><h1>Steam Achievement Collections</h1><p>Log in with Steam, import your library once, and build public achievement-hunting collections from any Steam game.</p><a className="steam" href={`${API}/auth/steam`}>Sign in through Steam</a></main>;
  return <main><header><div><h1>Steam Achievement Collections</h1>{user&&<p>Signed in as <b>{user.display_name}</b></p>}</div><nav>{['library','collections','browse','profile','settings'].map(p=><button key={p} className={page===p?'active':''} onClick={()=>setPage(p)}>{p[0].toUpperCase()+p.slice(1)}</button>)}<button onClick={()=>{localStorage.removeItem('steamToken');setToken(null)}}>Log out</button></nav></header>{status&&<p className="status">{status}</p>}
    {!user?.library_imported_at&&<section className="panel"><h2>First-time setup</h2><p>This imports your owned game list once. Achievements are synced later in small batches.</p><button className="primary" onClick={initialImport}>Import Steam library</button></section>}
    {page==='library'&&<><section className="controls"><input placeholder="Search owned games..." value={query} onChange={e=>setQuery(e.target.value)}/><select value={tag} onChange={e=>setTag(e.target.value)}><option value="all">All tags</option>{Object.keys(TAGS).map(t=><option key={t}>{t}</option>)}</select><select value={sort} onChange={e=>setSort(e.target.value)}><option value="alpha">Alphabetical</option><option value="percent">Achievement %</option><option value="playtime">Playtime</option></select><button disabled={syncing||!games.length} onClick={()=>syncAchievements(false)}>Sync next achievement batch</button></section><section className="grid">{visibleGames.map(game=><GameCard key={game.appid} game={game} featured={settings.featured_game_ids.map(String).includes(String(game.appid))} onFeature={()=>toggleFeatured(game.appid)} onViewAchievements={()=>setAchievementGame(game)}/>)}</section></>}
    {page==='collections'&&<Collections token={token} collections={collections} reload={loadCollections}/>} 
    {page==='browse'&&<BrowseCollections token={token} reloadMine={loadCollections}/>} 
    {page==='profile'&&<Profile user={user} settings={settings} saveProfile={saveProfile} games={games} featuredGames={featuredGames} stats={stats} toggleFeatured={toggleFeatured} collections={collections} onViewAchievements={setAchievementGame}/>} 
    {achievementGame&&<AchievementModal token={token} game={achievementGame} onClose={()=>setAchievementGame(null)}/>}
    {page==='settings'&&<Settings refreshLibrary={refreshLibrary} syncAchievements={syncAchievements} syncing={syncing} user={user} stats={stats} settings={settings} saveProfile={saveProfile}/>} 
  </main>;
}

function GameCard({game,featured,onFeature,onViewAchievements}){ return <article className="card game-card"><img className="game-art" src={gameImage(game)} alt={`${game.name} capsule art`} onError={e=>e.currentTarget.src=imgUrl(game.appid)}/><div className="card-title"><h2>{game.name}</h2>{onFeature&&<button className="mini" onClick={onFeature}>{featured?'★':'☆'}</button>}</div><p>{Math.round((game.playtime_forever||0)/60)} hours played</p><Progress achievements={game.achievements}/><p className="muted">Last sync: {game.achievement_last_synced_at||'Never'}</p><div>{game.tags?.map(t=><small key={t}>{t}</small>)}</div>{onViewAchievements&&<button className="ghost" onClick={onViewAchievements}>View achievements</button>}</article>; }
function Progress({achievements}){ const p=achievements.percent??0; return <><div className="bar"><span style={{width:`${p}%`}}/></div><p>{achievements.percent===null?'No synced/public achievement data':`${achievements.unlocked}/${achievements.total} achievements • ${achievements.percent}%`}</p></>; }

function AchievementModal({token,game,onClose}){ const [items,setItems]=useState(null); const [error,setError]=useState(''); useEffect(()=>{ api(token,`/api/achievements/${game.appid}`).then(d=>setItems(d.achievements||[])).catch(e=>setError(e.message)); },[game.appid]); return <div className="modal-backdrop" onClick={onClose}><section className="modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={onClose}>×</button><img className="modal-hero" src={gameImage(game)} alt={`${game.name} capsule art`}/><h2>{game.name} Achievements</h2><p className="muted">Displays achievement icon, name, and description from cached Steam schema data when available.</p>{error&&<p className="status">{error}</p>}{!items&&<p>Loading achievements...</p>}{items&&items.length===0&&<p>No synced achievements yet. Run an achievement batch sync first, or preview public achievements from a collection.</p>}<div className="achievement-list">{items?.map(a=><article className={a.unlocked?'achievement unlocked':'achievement locked'} key={a.achievement_api_name}><img src={(a.unlocked?a.icon_url:a.icon_gray_url)||a.icon_url||a.icon_gray_url||''} alt="" onError={e=>e.currentTarget.style.display='none'}/><div><h3>{a.display_name||a.achievement_api_name}</h3><p>{a.description||'No description available.'}</p>{a.unlocked? <small>Unlocked{a.unlock_time?` • ${new Date(a.unlock_time*1000).toLocaleDateString()}`:''}</small> : <small>Locked</small>}</div></article>)}</div></section></div>; }

function Collections({token,collections,reload}){ const [selected,setSelected]=useState(null); const [draft,setDraft]=useState({name:'',description:'',visibility:'public'}); async function create(){ if(!draft.name.trim()) return; const d=await api(token,'/api/collections',{method:'POST',body:JSON.stringify(draft)}); setDraft({name:'',description:'',visibility:'public'}); setSelected(d.collection); await reload(); } return <section className="two-col"><aside className="panel"><h2>Create Collection</h2><input placeholder="Final Fantasy Achievement Collection" value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/><textarea placeholder="What is this collection for?" value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})}/><select value={draft.visibility} onChange={e=>setDraft({...draft,visibility:e.target.value})}><option value="public">Public</option><option value="private">Private</option></select><button className="primary" onClick={create}>Create</button><h3>My Collections</h3>{collections.mine.map(c=><CollectionRow key={c.id} c={c} onClick={()=>setSelected(c)}/>) }<h3>Saved to Profile</h3>{collections.saved.map(c=><CollectionRow key={c.id} c={c} onClick={()=>setSelected(c)}/>)}</aside><CollectionEditor token={token} selected={selected} reload={async()=>{await reload(); if(selected){const d=await api(token,`/api/collections/${selected.id}`); setSelected(d.collection)}}}/></section>; }
function CollectionRow({c,onClick}){ return <button className="collection-row" onClick={onClick}><b>{c.name}</b><span>{c.game_count||0} games • by {c.owner_name||'you'}</span></button>; }
function CollectionEditor({token,selected,reload}){ const [detail,setDetail]=useState(null); const [q,setQ]=useState(''); const [results,setResults]=useState([]); const [schema,setSchema]=useState(null); useEffect(()=>{ if(selected) api(token,`/api/collections/${selected.id}`).then(setDetail); },[selected?.id]); async function search(){ if(q.trim().length<2) return; const d=await api(token,`/api/steam/search?q=${encodeURIComponent(q)}`); setResults(d.results); } async function add(app){ await api(token,`/api/collections/${detail.collection.id}/games`,{method:'POST',body:JSON.stringify(app)}); const d=await api(token,`/api/collections/${detail.collection.id}`); setDetail(d); } async function remove(appid){ await api(token,`/api/collections/${detail.collection.id}/games/${appid}`,{method:'DELETE'}); const d=await api(token,`/api/collections/${detail.collection.id}`); setDetail(d); } async function preview(appid){ const d=await api(token,`/api/apps/${appid}/schema`); setSchema(d); } if(!selected) return <section className="panel"><h2>Collection Builder</h2><p>Select a collection or create one. Collections can include games the user does not own.</p></section>; if(!detail) return <section className="panel">Loading...</section>; return <section className="panel"><h2>{detail.collection.name}</h2><p>{detail.collection.description}</p><div className="searchbar"><input placeholder="Search any Steam game..." value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')search()}}/><button onClick={search}>Search Steam</button></div><div className="search-results">{results.map(app=><div key={app.appid} className="result"><img src={app.wide||app.header||app.capsule} alt={`${app.name} capsule art`}/><span>{app.name}</span><button onClick={()=>add(app)}>Add</button><button onClick={()=>preview(app.appid)}>Preview achievements</button></div>)}</div><h3>Games in Collection</h3>{detail.games.map(g=><div className="row game-row" key={g.app_id}><img src={g.wide_capsule_url||g.header_url||g.capsule_url||imgUrl(g.app_id)} alt={`${g.game_name} capsule art`}/><span>{g.game_name}{!g.owned_by_me&&<em> not owned</em>}</span><span>{g.achievement_percent==null?'No personal sync':`${g.achievement_percent}%`}</span><button onClick={()=>preview(g.app_id)}>Achievements</button><button onClick={()=>remove(g.app_id)}>Remove</button></div>)}{schema&&<section className="schema"><h3>Achievement Preview for App {schema.appid}</h3><p className="muted">This uses a shared cached app schema, not a per-user achievement fetch.</p>{schema.achievements.length?schema.achievements.slice(0,30).map(a=><div className="achievement" key={a.achievement_api_name}>{a.icon_url&&<img src={a.icon_url}/>}<div><b>{a.display_name||a.achievement_api_name}</b><p>{a.description}</p></div></div>):<p>No public schema available.</p>}</section>}</section>; }

function BrowseCollections({token,reloadMine}){ const [q,setQ]=useState(''); const [results,setResults]=useState([]); async function search(){ const d=await api(token,`/api/collections/search?q=${encodeURIComponent(q)}`); setResults(d.results); } async function save(id){ await api(token,`/api/collections/${id}/save`,{method:'POST'}); await search(); await reloadMine(); } useEffect(()=>{ search(); },[]); return <section className="panel"><h2>Browse User-Created Collections</h2><p>Find achievement-hunting lists other users created and add them to your profile.</p><div className="searchbar"><input placeholder="Search collections, e.g. Final Fantasy" value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')search()}}/><button onClick={search}>Search</button></div><div className="grid">{results.map(c=><article className="card" key={c.id}><h2>{c.name}</h2><p>{c.description}</p><p className="muted">{c.game_count} games • by {c.owner_name}</p><button disabled={!!c.saved_by_me} onClick={()=>save(c.id)}>{c.saved_by_me?'Added to profile':'Add to profile'}</button></article>)}</div></section>; }

function Profile({user,settings,saveProfile,games,featuredGames,stats,toggleFeatured,collections,onViewAchievements}){ const displayName=settings.display_name||user?.display_name||'Steam User'; const savedCollections=collections.saved||[]; return <section className={`profile ${settings.layout_style}`}><aside className="customizer"><h2>Customize Profile</h2><label>Display name<input value={settings.display_name||''} onChange={e=>saveProfile({...settings,display_name:e.target.value})}/></label><label>Headline<input value={settings.headline||''} onChange={e=>saveProfile({...settings,headline:e.target.value})}/></label><label>Layout<select value={settings.layout_style} onChange={e=>saveProfile({...settings,layout_style:e.target.value})}><option value="hero">Hero</option><option value="sidebar">Sidebar</option><option value="compact">Compact</option></select></label><label>Achievement display<select value={settings.achievement_display_mode} onChange={e=>saveProfile({...settings,achievement_display_mode:e.target.value})}><option value="byGame">By game</option><option value="overall">Whole library</option><option value="showcase">Showcase</option><option value="collections">Achievement collections</option></select></label></aside><div className="profile-main"><section className="profile-hero-card">{user?.avatar_url&&<img className="avatar" src={user.avatar_url}/>}<div><h2>{displayName}</h2><p>{settings.headline}</p><div className="stats"><b>{stats.overallPercent}%</b><span>overall</span><b>{stats.perfectGames}</b><span>perfect</span><b>{savedCollections.length}</b><span>collections</span></div></div></section>{settings.achievement_display_mode==='overall'&&<Summary stats={stats}/>} {settings.achievement_display_mode==='byGame'&&<section className="grid">{featuredGames.map(g=><GameCard key={g.appid} game={g} featured onFeature={()=>toggleFeatured(g.appid)} onViewAchievements={()=>onViewAchievements(g)}/>)}</section>} {settings.achievement_display_mode==='collections'&&<section className="grid">{savedCollections.map(c=><article className="card" key={c.id}><h2>{c.name}</h2><p>{c.description}</p><p>{c.game_count} games</p></article>)}</section>}</div></section>; }
function Summary({stats}){ return <section className="panel"><h2>Whole Library Achievement Summary</h2><div className="big-percent">{stats.overallPercent}%</div><Progress achievements={{unlocked:stats.unlockedAchievements,total:stats.totalAchievements,percent:stats.overallPercent}}/><div className="summary-grid"><p><b>{stats.totalGames}</b><br/>games imported</p><p><b>{stats.achievementGames}</b><br/>with achievements</p><p><b>{stats.perfectGames}</b><br/>perfect games</p></div></section>; }
function Settings({refreshLibrary,syncAchievements,syncing,user,stats,settings,saveProfile}){ const swatches=['#3b82f6','#ef4444','#22c55e','#a855f7','#f97316','#06b6d4','#eab308','#ec4899']; return <section className="panel settings-panel"><h2>Settings & Sync Controls</h2><div className="accent-picker"><h3>Site highlight color</h3><p className="muted">This controls buttons, glows, progress bars, and animated highlights across your profile.</p><div className="swatches">{swatches.map(c=><button key={c} className={settings.accent_color===c?'swatch selected':'swatch'} style={{background:c}} title={c} onClick={()=>saveProfile({...settings,accent_color:c})}/>)}</div><label>Custom color<input type="color" value={settings.accent_color||'#3b82f6'} onChange={e=>saveProfile({...settings,accent_color:e.target.value})}/></label></div><p><b>Library import:</b> {user?.library_imported_at||'Not imported yet'}</p><p><b>Games saved:</b> {stats.totalGames}</p><div className="stack"><button className="primary" onClick={refreshLibrary}>Manually update game library</button><p className="muted">One owned-games request, then adds only missing games and updates playtime. It does not fetch achievements for every game.</p><button disabled={syncing} onClick={()=>syncAchievements(false)}>Sync next achievement batch</button><p className="muted">Fetches only a small batch of games that are due for sync.</p><button disabled={syncing} onClick={()=>syncAchievements(true)}>Force sync next batch</button></div></section>; }

createRoot(document.getElementById('root')).render(<App/>);
