import React, { useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './style.css';

const API = import.meta.env.VITE_API_URL || 'http://localhost:8787';
const TAGS = { RPG: ['final fantasy','dragon quest','persona','tales of','ys','trails'], Action: ['assassin','dark souls','monster hunter','resident evil'], Indie: ['hollow knight','celeste','stardew','hades'], Strategy: ['civilization','xcom','total war'] };
function imgUrl(appid){ return `https://cdn.cloudflare.steamstatic.com/steam/apps/${appid}/capsule_616x353.jpg`; }
function gameImage(game){ return game.wide_capsule_url || game.header_url || game.capsule_url || imgUrl(game.appid || game.app_id); }
function hydrateGame(g){ const name=(g.name||'').toLowerCase(); return { ...g, tags:Object.entries(TAGS).filter(([,terms])=>terms.some(t=>name.includes(t))).map(([tag])=>tag), achievements:g.achievements||{total:g.achievement_total??0,unlocked:g.achievement_unlocked??0,percent:g.achievement_percent??null} }; }

const DEMO_GAMES = [
  hydrateGame({appid:39140,name:'FINAL FANTASY VII',playtime_forever:3120,achievement_total:36,achievement_unlocked:20,achievement_percent:56}),
  hydrateGame({appid:1173780,name:'FINAL FANTASY II',playtime_forever:740,achievement_total:24,achievement_unlocked:10,achievement_percent:42}),
  hydrateGame({appid:1173820,name:'FINAL FANTASY VI',playtime_forever:1880,achievement_total:37,achievement_unlocked:37,achievement_percent:100}),
  hydrateGame({appid:292030,name:'The Witcher 3: Wild Hunt',playtime_forever:4920,achievement_total:78,achievement_unlocked:50,achievement_percent:64}),
  hydrateGame({appid:367520,name:'Hollow Knight',playtime_forever:2210,achievement_total:63,achievement_unlocked:41,achievement_percent:65}),
  hydrateGame({appid:105600,name:'Terraria',playtime_forever:6600,achievement_total:115,achievement_unlocked:89,achievement_percent:77})
];
const DEMO_COLLECTIONS = { mine:[{id:1,name:'Final Fantasy Pixel + Classics',description:'A curated achievement hunt through the classic Final Fantasy games on Steam.',game_count:6,owner_name:'KnightExcalibur'},{id:2,name:'Long RPG Completion Runs',description:'Big RPGs worth chipping away at over months.',game_count:12,owner_name:'KnightExcalibur'}], saved:[{id:3,name:'Metroidvania Mastery',description:'Community list of excellent metroidvania completions.',game_count:9,owner_name:'Community'}] };
const DEMO_ACHIEVEMENTS = [
  {achievement_api_name:'first_win',display_name:'First Victory',description:'Win your first battle.',unlocked:true,icon_url:'https://cdn.cloudflare.steamstatic.com/steamcommunity/public/images/apps/39140/0b7aa19cc9f3e7.jpg'},
  {achievement_api_name:'treasure_hunter',display_name:'Treasure Hunter',description:'Open 100 treasure chests.',unlocked:false,icon_gray_url:'https://cdn.cloudflare.steamstatic.com/steamcommunity/public/images/apps/39140/0b7aa19cc9f3e7.jpg'},
  {achievement_api_name:'completionist',display_name:'Master Completionist',description:'Unlock every achievement in the game.',unlocked:false,icon_gray_url:'https://cdn.cloudflare.steamstatic.com/steamcommunity/public/images/apps/39140/0b7aa19cc9f3e7.jpg'}
];

function App(){
  const [page,setPage]=useState('library'); const [query,setQuery]=useState(''); const [tag,setTag]=useState('all'); const [sort,setSort]=useState('alpha'); const [achievementGame,setAchievementGame]=useState(null); const [accent,setAccent]=useState('#3b82f6');
  document.documentElement.style.setProperty('--accent', accent);
  const games = DEMO_GAMES;
  const settings={featured_game_ids:['1173820','105600'],featured_collection_ids:[1,3],layout_style:'hero',achievement_display_mode:'byGame',card_density:'comfortable',accent_color:accent};
  const stats=useMemo(()=>{ const total=games.reduce((s,g)=>s+g.achievements.total,0); const unlocked=games.reduce((s,g)=>s+g.achievements.unlocked,0); return {totalGames:games.length,achievementGames:games.length,totalAchievements:total,unlockedAchievements:unlocked,perfectGames:games.filter(g=>g.achievements.percent===100).length,overallPercent:Math.round(unlocked/total*100)}; },[games]);
  const visibleGames=useMemo(()=>{ let list=games.filter(g=>g.name?.toLowerCase().includes(query.toLowerCase())); if(tag!=='all') list=list.filter(g=>g.tags.includes(tag)); if(sort==='alpha') list.sort((a,b)=>a.name.localeCompare(b.name)); if(sort==='percent') list.sort((a,b)=>(b.achievements.percent??-1)-(a.achievements.percent??-1)); if(sort==='playtime') list.sort((a,b)=>(b.playtime_forever||0)-(a.playtime_forever||0)); return list; },[query,tag,sort]);
  const featuredGames=games.filter(g=>settings.featured_game_ids.includes(String(g.appid)));
  return <main><header><div><h1>CheevoCollections</h1><p>Demo mode: Steam login and live syncing will turn on after the backend is deployed.</p></div><nav>{['library','collections','browse','profile','settings'].map(p=><button key={p} className={page===p?'active':''} onClick={()=>setPage(p)}>{p[0].toUpperCase()+p.slice(1)}</button>)}<a className="steam" href={`${API}/auth/steam`}>Sign in through Steam</a></nav></header>
    <section className="hero panel"><h2>Build and share achievement-hunting collections.</h2><p>Create collections like Final Fantasy 100%, Resident Evil Marathon, Steam JRPG Classics, or Metroidvania Mastery. Users will be able to follow collections and pin them to their profiles.</p></section>
    {page==='library'&&<><section className="controls"><input placeholder="Search demo games..." value={query} onChange={e=>setQuery(e.target.value)}/><select value={tag} onChange={e=>setTag(e.target.value)}><option value="all">All tags</option>{Object.keys(TAGS).map(t=><option key={t}>{t}</option>)}</select><select value={sort} onChange={e=>setSort(e.target.value)}><option value="alpha">Alphabetical</option><option value="percent">Achievement %</option><option value="playtime">Playtime</option></select></section><section className="grid">{visibleGames.map(game=><GameCard key={game.appid} game={game} featured={settings.featured_game_ids.includes(String(game.appid))} onViewAchievements={()=>setAchievementGame(game)}/>)}</section></>}
    {page==='collections'&&<section className="two-col"><aside className="panel"><h2>Create Collection</h2><input placeholder="Final Fantasy Achievement Collection"/><textarea placeholder="What is this collection for?"/><button className="primary">Create demo collection</button><h3>My Collections</h3>{DEMO_COLLECTIONS.mine.map(c=><CollectionRow key={c.id} c={c}/>)}</aside><section className="panel"><h2>Collection Builder</h2><p>Search any Steam game, add it to a collection, and preview public achievement data. This is mocked until the backend is connected.</p>{games.slice(0,4).map(g=><div className="row game-row" key={g.appid}><img src={gameImage(g)} alt=""/><span>{g.name}</span><button>Add</button><button onClick={()=>setAchievementGame(g)}>Achievements</button></div>)}</section></section>}
    {page==='browse'&&<section className="grid">{[...DEMO_COLLECTIONS.mine,...DEMO_COLLECTIONS.saved].map(c=><article className="card" key={c.id}><h2>{c.name}</h2><p>{c.description}</p><p>{c.game_count} games • by {c.owner_name}</p><button className="primary">Add to profile</button></article>)}</section>}
    {page==='profile'&&<Profile settings={settings} games={games} featuredGames={featuredGames} stats={stats} collections={DEMO_COLLECTIONS} onViewAchievements={setAchievementGame}/>} 
    {page==='settings'&&<section className="panel"><h2>Settings</h2><p>Pick the site highlight color.</p><input type="color" value={accent} onChange={e=>setAccent(e.target.value)}/><h3>Future live options</h3><button disabled>Refresh Steam library</button><button disabled>Sync next achievement batch</button><p className="muted">These will activate after the Cloudflare Worker backend is deployed.</p></section>}
    {achievementGame&&<AchievementModal game={achievementGame} onClose={()=>setAchievementGame(null)}/>} </main>;
}
function GameCard({game,featured,onViewAchievements}){ return <article className="card game-card"><img className="game-art" src={gameImage(game)} alt={`${game.name} capsule art`}/><div className="card-title"><h2>{game.name}</h2><button className="mini">{featured?'★':'☆'}</button></div><p>{Math.round((game.playtime_forever||0)/60)} hours played</p><Progress achievements={game.achievements}/><div>{game.tags?.map(t=><small key={t}>{t}</small>)}</div><button className="ghost" onClick={onViewAchievements}>View achievements</button></article>; }
function Progress({achievements}){ const p=achievements.percent??0; return <><div className="bar"><span style={{width:`${p}%`}}/></div><p>{achievements.unlocked}/{achievements.total} achievements • {achievements.percent}%</p></>; }
function CollectionRow({c}){ return <button className="collection-row"><b>{c.name}</b><span>{c.game_count||0} games • by {c.owner_name||'you'}</span></button>; }
function Profile({settings,games,featuredGames,stats,collections,onViewAchievements}){ return <><section className="profile-hero panel"><h2>KnightExcalibur's Achievement Shelf</h2><p>Curated Steam completion goals, featured games, and followed achievement collections.</p><div className="stats"><b>{stats.totalGames}</b><span>Games</span><b>{stats.overallPercent}%</b><span>Overall</span><b>{stats.perfectGames}</b><span>Perfected</span></div></section><h2>Featured Games</h2><section className="grid">{featuredGames.map(g=><GameCard key={g.appid} game={g} featured onViewAchievements={()=>onViewAchievements(g)}/>)}</section><h2>Pinned Collections</h2><section className="grid">{[...collections.mine,...collections.saved].map(c=><article className="card" key={c.id}><h2>{c.name}</h2><p>{c.description}</p><p>{c.game_count} games</p></article>)}</section></>; }
function AchievementModal({game,onClose}){ return <div className="modal-backdrop" onClick={onClose}><section className="modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={onClose}>×</button><img className="modal-hero" src={gameImage(game)} alt={`${game.name} capsule art`}/><h2>{game.name} Achievements</h2><p className="muted">Demo achievement icon, name, description, and locked/unlocked state.</p><div className="achievement-list">{DEMO_ACHIEVEMENTS.map(a=><article className={a.unlocked?'achievement unlocked':'achievement locked'} key={a.achievement_api_name}><img src={(a.unlocked?a.icon_url:a.icon_gray_url)||''} alt=""/><div><h3>{a.display_name}</h3><p>{a.description}</p><small>{a.unlocked?'Unlocked':'Locked'}</small></div></article>)}</div></section></div>; }

createRoot(document.getElementById('root')).render(<App/>);
